spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    platform: h2
    url: jdbc:h2:./development.h2.db
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: H2

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE