INSERT INTO USER(ID, USERNAME, AGE) VALUES (123, 'clark', 33);
INSERT INTO USER(ID, USERNAME, AGE) VALUES (124, 'kevin', 8);

INSERT INTO MOVIE(ID, TITLE, RATING) VALUES(123, 'Man of Steel', 'G');
INSERT INTO MOVIE(ID, TITLE, RATING) VALUES(124, 'Conjuro', 'PG_13');
